version: "3.6"

services:

  dashboard-switcher:
    image: nginx:1.27.1-alpine
    container_name: dashboard-switcher
    restart: always
    ports:
      - "127.0.0.1:3002:80"
    volumes:
      - ${PWD}/public:/usr/share/nginx/html:ro
    networks:
      - shared-rev-proxy

networks:
  shared-rev-proxy:
    external: true